server:
  port: 8091
  
test: test: {cipher}AQCGIKc/K6VVnmgzrSi3q5Iar4edvHm2GbNpu8lDHOXQDDz07wphMYFOKu/NVAmc/vjhOtitAocE5EKwpzmPXnAggQQpbQ/hAByQ0NgCojZR8j5kbwkFiQa9liPNTezzO+B/A/Hydix2XAdNgWSFHXXyNWJ7Q614JIKlNeLcZgOow9pwpYfQBSiIXtNHlbx+1S5hwlHBYTgZWV+74oXxe0bfflKGhG8NTcTUgf+XWtHfQIXGX+WQlXWsUcFBpYPMACSUrFRvRYUUDvsl6eODEGfwVcBa9Cnecp6R0qJo3KyUWkoBQ4i2+Ng3R4o5WWuQLTphZgaigsqBoDtYXXDe8kN/Qfl2/rmiZgN4wdt6a7eZ19Uzb5NfdYzuqORzI/6a3b8=